version: 2.1

# 実行するjob
jobs:
  # buildするjob
  build:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: docker-compose -f ./back/docker-compose.yml build
          command: docker-compose -f ./back/docker-compose.yml build
      - run:
          name: docker-compose -f ./front/docker-compose.yml build
          command: docker-compose -f ./front/docker-compose.yml build
  # testするjob
  test:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: docker-compose -f ./back/docker-compose.yml up -d
          command: docker-compose -f ./back/docker-compose.yml up -d
      - run:
          name: docker-compose -f ./front/docker-compose.yml up -d
          command: docker-compose -f ./front/docker-compose.yml up -d
      - run: sleep 10
      - run:
          name: docker-compose -f ./back/docker-compose.yml run app rails db:create RAILS_ENV=test
          command: docker-compose -f ./back/docker-compose.yml run app rails db:create RAILS_ENV=test
      - run:
          name: docker-compose -f ./back/docker-compose.yml run app rails db:migrate RAILS_ENV=test
          command: docker-compose -f ./back/docker-compose.yml run app rails db:migrate RAILS_ENV=test
      - run:
          name: docker-compose -f ./back/docker-compose.yml run app rails db:seed RAILS_ENV=test
          command: docker-compose -f ./back/docker-compose.yml run app rails db:seed RAILS_ENV=test
      - run:
          name: docker-compose -f ./back/docker-compose.yml run app bundle exec rspec spec
          command: docker-compose -f ./back/docker-compose.yml run app bundle exec rspec spec
      - run:
          name: docker-compose -f ./front/docker-compose.yml run front yarn install
          command: docker-compose -f ./front/docker-compose.yml run front yarn install
        # フロントエンド側テスト
      - run:
          name: docker-compose -f ./front/docker-compose.yml run front yarn run test
          command: docker-compose -f ./front/docker-compose.yml run front yarn test
      - run:
          name: docker-compose -f ./back/docker-compose.yml down
          command: docker-compose -f ./back/docker-compose.yml down
      - run:
          name: docker-compose -f ./front/docker-compose.yml down
          command: docker-compose -f ./front/docker-compose.yml down

# 順番を制御するworkflow
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
