## お知らせ
# 一覧のデフォルト最大表示件数
default_infomations_limit: 25

## 記事
# 一覧のデフォルト最大表示件数
default_articles_limit: 30

## 獲得ポイント
# 記事作成時獲得ポイント
article_create_obtained_point: 5

# 記事お気に入りされた時の獲得ポイント
article_favorite_author_obtained_point: 2

# 記事お気に入りした時の獲得ポイント
article_favorite_reader_obtained_point: 1

# 防災タスク完了時時獲得ポイント
task_complete_obtained_point: 5

## ユーザー
# 一覧のデフォルト最大表示件数
default_users_limit: 20
# ゲストアカウント削除の猶予期間（単位：日）
destroy_schedule_days: 1

## 避難所
# 一覧のデフォルト最大表示件数
default_shelters_limit: 25

# 避難所登録時時獲得ポイント
shelter_registration_obtained_point: 5
